import { Router } from "express";
import { PostController } from "../controllers";
const postsRouter = Router();
postsRouter.get("/", PostController.index);
postsRouter.post("/", PostController.create);
postsRouter.get("/:post", PostController.show);
postsRouter.put("/:post", PostController.update);
postsRouter.delete("/:post", PostController.delete);
postsRouter.patch("/:post", PostController.like);
export default postsRouter;
